export const DEFAULT_BABEL_PHRASES = [
  'The sun rises in the east.',
  'Where is the nearest tavern?',
  'I seek knowledge and wisdom.',
  'The road ahead is long and winding.',
  'May your blade stay sharp.',
  'Water flows ever downhill.',
  'The stars guide weary travelers.',
  'Time waits for no one.',
  'A wise soul listens before speaking.',
  'The wind carries many secrets.',
  'Fortune favors the bold.',
  'Every journey begins with a single step.',
  'The forest remembers what we forget.',
  'Shadows grow long at twilight.',
  'A stranger is just a friend unmet.',
  'The harvest moon rises tonight.',
  'Beware the calm before the storm.',
  'Trust is earned, never given.',
  'The old stones hold ancient power.',
  'Dawn breaks over the mountains.',
  'A skilled healer is worth ten warriors.',
  'The river knows the way to the sea.',
  'Courage is not the absence of fear.',
  'The market opens at first light.',
  'Legends are born from truth.',
  'A warm fire wards off the darkness.',
  'The dragon sleeps beneath the mountain.',
  'Knowledge is the greatest treasure.',
  'The tide turns for all who wait.',
  'Speak softly and carry a big sword.',
];
